Resources:
  GlueSourceSGdbs:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Sub vpc-mygluejobs
      GroupDescription: Security Group to allow AWS services to access on-premise DBs
  GlueTargetSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId: !Sub vpc-intranet
      GroupDescription: Sample target security group
  OutboundRule: 
    Type: AWS::EC2::SecurityGroupEgress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      DestinationSecurityGroupId:
        Fn::GetAtt:
          - TargetSG: !Sub Intranet-SG
          - GroupId: !Sub SGR-Intranet
      GroupId:
        Fn::GetAtt:
          - SourceSG: !Sub SGR-mygluejob
          - GroupId: !Sub SGR-myapp
  InboundRule:
    Type: AWS::EC2::SecurityGroupIngress
    Properties:
      IpProtocol: tcp
      FromPort: 0
      ToPort: 65535
      SourceSecurityGroupId:
        Fn::GetAtt:
          - SourceSG: !Sub Intranet-SG
          - GroupId: !Sub SGR-Intranet
      GroupId:
        Fn::GetAtt:
          - TargetSG: !Sub SGR-mygluejob
          - GroupId: !Sub SGR-myapp

#Additional security groups

#SecurityGroupIngressMYSERVICE:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#        Description: "Allow additional port(s)"
#        CidrIp: !Sub "${MyIp}"
#        IpProtocol: tcp
#        FromPort: XX
#        ToPort: XX

#SecurityGroupIngressHTTP:
#    Type: AWS::EC2::SecurityGroupIngress
#    Properties:
#        Description: "Allow HTTP inbound traffic"
#        GroupId: !Ref SecurityGroup
#        CidrIp: 0.0.0.0/0
#        IpProtocol: tcp
#        FromPort: 80
#        ToPort: 80

#SecurityGroupEgress:
#    Type: AWS::EC2::SecurityGroupEgress
#    Properties:
#        Description: "Allow all outbound traffic"
#        GroupId: !Ref SecurityGroup
#        CidrIp: 0.0.0.0/0  
#        IpProtocol: tcp
#        FromPort: 80
#        ToPort: 80