---
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  GLUESGJOBS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows traffic from all ports
#      VpcId: !Ref MyVPC
      VpcId: Equals [!Ref MyVPC]
      SecurityGroupIngress:
      - IpProtocol: -1
        FromPort: '0'
        ToPort: '65535'
        SourceSecurityGroupdId: !Ref SourceSecurityIngress
        SourcePrefixListId: !Ref SourcePrefixListId
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: '0'
        ToPort: '65535'
        SourceSecurityGroupdId: !Ref SourceSecurityIngress

Outputs:
  SecurityGroupID:
    Description: Security Group ID
    Value: !Ref GLUESGJOBS
    Export:
      Name: !Sub "${AWS::StackName}-SecurityGroupId" 
