---
AWSTemplateFormatVersion: '2010-09-09'
Description: HTTPS - Security Group to access on-prem services

Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: VPC for the Intranet Security Group
  Name:
    Type: String
    Description: ecgrp-glue-self-ref
  Description:
    Type: String
    Description: SG-glue-self-ref
    AllowedValues:
      - GLUESG

Conditions:
  SourceSecurityGroupId: !Equals [!Ref VPC, GLUESG]

Resources:
  GLUESG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Ref: Description
      VpcId: Equals [!Ref VPC]
      SecurityGroupIngress:
      - IpProtocol: -1
        FromPort: '0'
        ToPort: '65535'
#      - IpProtocol: tcp
#        CidrIp: 54.228.16.0/26
#        FromPort: '443'
#        ToPort: '443'
      SecurityGroupEgress:
      - IpProtocol: -1
        FromPort: '0'
        ToPort: '65535'

Outputs:
  SecurityGroupID:
    Description: Security Group ID
    Value:
      Ref: GLUESG
